name: build linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [debug, release]
        platform: [x86_64]
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'recursive'
      - shell: bash
        run: |
          sudo apt install libxcb1-dev libvulkan-dev qtbase5-dev
          ./build-linux/build.sh "${{matrix.configuration}}"
      - uses: actions/upload-artifact@main
        with:
          name: Brioche-Puppet-Linux-${{matrix.platform}}-${{matrix.configuration}}
          path: |
            ./build-linux/bin/${{matrix.configuration}}/${{matrix.platform}}/BRX-Puppet
            ./build-linux/bin/${{matrix.configuration}}/${{matrix.platform}}/BRX-OpenFileDialog
            ./build-linux/bin/${{matrix.configuration}}/${{matrix.platform}}/**/*.so
